# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-28 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gjc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='标题')),
            ],
            options={
                'verbose_name': '关键词',
                'verbose_name_plural': '关键词',
            },
        ),
        migrations.CreateModel(
            name='yqin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_time', models.CharField(max_length=32, unique=True, verbose_name='发布时间')),
                ('title', models.CharField(max_length=300, verbose_name='标题')),
                ('hf', models.CharField(max_length=30, verbose_name='回复数量')),
                ('ck', models.CharField(max_length=32, verbose_name='查看量')),
                ('url', models.CharField(max_length=64, verbose_name='连接')),
                ('ly', models.CharField(max_length=64, verbose_name='来源网站')),
                ('gjc', models.CharField(max_length=32, verbose_name='关键词')),
            ],
            options={
                'verbose_name': '临时舆情信息',
                'verbose_name_plural': '临时舆情信息',
            },
        ),
        migrations.CreateModel(
            name='yqin1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_time', models.CharField(max_length=32, unique=True, verbose_name='发布时间')),
                ('title', models.CharField(max_length=300, verbose_name='标题')),
                ('hf', models.CharField(max_length=30, verbose_name='回复数量')),
                ('ck', models.CharField(max_length=32, verbose_name='查看量')),
                ('url', models.CharField(max_length=64, verbose_name='连接')),
                ('ly', models.CharField(max_length=64, verbose_name='来源网站')),
                ('gjc', models.CharField(max_length=32, verbose_name='关键词')),
            ],
            options={
                'verbose_name': '实时舆情信息',
                'verbose_name_plural': '实时舆情信息',
            },
        ),
        migrations.CreateModel(
            name='yqout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_time', models.CharField(max_length=32, unique=True, verbose_name='发布时间')),
                ('title', models.CharField(max_length=300, verbose_name='标题')),
                ('hf', models.CharField(max_length=30, verbose_name='回复数量')),
                ('ck', models.CharField(max_length=32, verbose_name='查看量')),
                ('url', models.CharField(max_length=64, verbose_name='连接')),
                ('ly', models.CharField(max_length=64, verbose_name='来源网站')),
                ('gjc', models.CharField(max_length=32, verbose_name='关键词')),
            ],
            options={
                'verbose_name': '舆情信息',
                'verbose_name_plural': '舆情信息',
            },
        ),
        migrations.CreateModel(
            name='yqout1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_time', models.CharField(max_length=32, unique=True, verbose_name='发布时间')),
                ('title', models.CharField(max_length=300, verbose_name='标题')),
                ('hf', models.CharField(max_length=30, verbose_name='回复数量')),
                ('ck', models.CharField(max_length=32, verbose_name='查看量')),
                ('url', models.CharField(max_length=64, verbose_name='连接')),
                ('ly', models.CharField(max_length=64, verbose_name='来源网站')),
                ('gjc', models.CharField(max_length=32, verbose_name='关键词')),
            ],
            options={
                'verbose_name': '实时舆情信息',
                'verbose_name_plural': '实时舆情信息',
            },
        ),
    ]
