# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-28 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuqing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yqin',
            name='url',
            field=models.CharField(max_length=500, verbose_name='连接'),
        ),
        migrations.AlterField(
            model_name='yqin1',
            name='url',
            field=models.CharField(max_length=500, verbose_name='连接'),
        ),
        migrations.AlterField(
            model_name='yqout',
            name='url',
            field=models.CharField(max_length=500, verbose_name='连接'),
        ),
        migrations.AlterField(
            model_name='yqout1',
            name='url',
            field=models.CharField(max_length=500, verbose_name='连接'),
        ),
    ]
