# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-28 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuqing', '0002_auto_20190228_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yqin',
            name='publish_time',
            field=models.CharField(max_length=32, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='yqin1',
            name='publish_time',
            field=models.CharField(max_length=32, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='yqout',
            name='publish_time',
            field=models.CharField(max_length=32, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='yqout1',
            name='publish_time',
            field=models.CharField(max_length=32, verbose_name='发布时间'),
        ),
    ]
